// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dmitry_efimov_kt_31_20.Database;

#nullable disable

namespace dmitryefimovkt3120.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dmitry_efimov_kt_31_20.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id")
                        .HasComment("Идентификатор записи группы");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_group_name")
                        .HasComment("Название группы");

                    b.HasKey("GroupId")
                        .HasName("pk_cd_group_group_id");

                    b.ToTable("cd_group", (string)null);
                });

            modelBuilder.Entity("dmitry_efimov_kt_31_20.Models.Ratings", b =>
                {
                    b.Property<int>("RaingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ratings_id")
                        .HasComment("Идентификатор экзамена");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaingsId"));

                    b.Property<int>("GradeRatings")
                        .HasMaxLength(100)
                        .HasColumnType("int4")
                        .HasColumnName("c_ratings_grade")
                        .HasComment("Оценка");

                    b.Property<string>("RatingsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_ratings_name")
                        .HasComment("Название экзамена");

                    b.HasKey("RaingsId")
                        .HasName("pk_cd_ratings_ratings_id");

                    b.ToTable("cd_ratings", (string)null);
                });

            modelBuilder.Entity("dmitry_efimov_kt_31_20.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_id")
                        .HasComment("Идентификатор записи студента");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_firstname")
                        .HasComment("Имя студента");

                    b.Property<int>("GroupId")
                        .HasColumnType("int4")
                        .HasColumnName("f_group_id")
                        .HasComment("Идентификатор группы");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_lastname")
                        .HasComment("Фамилия студента");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_middlename")
                        .HasComment("Отчество студента");

                    b.Property<int>("RatingsId")
                        .HasColumnType("int4")
                        .HasColumnName("f_ratings_id")
                        .HasComment("Оценка");

                    b.Property<int>("TestId")
                        .HasColumnType("int4")
                        .HasColumnName("f_test_id")
                        .HasComment("Зачет");

                    b.HasKey("StudentId")
                        .HasName("pk_cd_student_student_id");

                    b.HasIndex(new[] { "GroupId" }, "idx_cd_student_fk_f_group_id");

                    b.HasIndex(new[] { "RatingsId" }, "idx_cd_student_fk_f_ratings_id");

                    b.HasIndex(new[] { "TestId" }, "idx_cd_student_fk_f_test_id");

                    b.ToTable("cd_student", (string)null);
                });

            modelBuilder.Entity("dmitry_efimov_kt_31_20.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("test_id")
                        .HasComment("Идентификатор зачета");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestId"));

                    b.Property<int>("IsTheTest")
                        .HasMaxLength(100)
                        .HasColumnType("int4")
                        .HasColumnName("c_test_ist")
                        .HasComment("Зачет или нет");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_test_name")
                        .HasComment("Название зачета");

                    b.HasKey("TestId")
                        .HasName("pk_cd_test_test_id");

                    b.ToTable("cd_test", (string)null);
                });

            modelBuilder.Entity("dmitry_efimov_kt_31_20.Models.Student", b =>
                {
                    b.HasOne("dmitry_efimov_kt_31_20.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_group_id");

                    b.HasOne("dmitry_efimov_kt_31_20.Models.Ratings", "Ratings")
                        .WithMany()
                        .HasForeignKey("RatingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_ratings_id");

                    b.HasOne("dmitry_efimov_kt_31_20.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_test_id");

                    b.Navigation("Group");

                    b.Navigation("Ratings");

                    b.Navigation("Test");
                });
#pragma warning restore 612, 618
        }
    }
}
